# Generated by Django 2.2.16 on 2020-10-12 12:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=128)),
                ('massage', models.TextField()),
            ],
            options={
                'verbose_name': 'Massage',
                'verbose_name_plural': 'Massages',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.PositiveSmallIntegerField(choices=[(1, 'USD'), (2, 'UER')], verbose_name='Currency')),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (3, 'Vkurse'), (4, 'Fixer'), (5, 'Oschadbank'), (6, 'Prostobank'), (7, 'Minfin'), (8, 'Ukrgazbank'), (9, 'Pumb'), (10, 'Pravex'), (11, 'Alphabank')], verbose_name='Bank')),
                ('buy', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Buy')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sale')),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 10, 12, 12, 30, 29, 430407, tzinfo=utc), verbose_name='Update time')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banks', models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (3, 'Vkurse'), (4, 'Fixer'), (5, 'Oschadbank'), (6, 'Prostobank'), (7, 'Minfin'), (8, 'Ukrgazbank'), (9, 'Pumb'), (10, 'Pravex'), (11, 'Alphabank')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
