# Generated by Django 2.2.16 on 2020-10-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='buy',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Buy'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'USD'), (2, 'UER')], verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sale',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (3, 'Vkurse'), (4, 'Fixer'), (5, 'Oschadbank'), (6, 'Prostobank'), (7, 'Minfin'), (8, 'Ukrgazbank'), (9, 'Pumb'), (10, 'Pravex'), (11, 'Alphabank')], verbose_name='Bank'),
        ),
    ]
