# Flake8: noqa
# Generated by Django 2.2.16 on 2020-12-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Massage', 'verbose_name_plural': 'Massages'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'permissions': [('full_edit', 'full edit')], 'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
    ]
