# Generated by Django 2.2.16 on 2020-10-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (3, 'Vkurse'), (4, 'fixer'), (5, 'oschadbank'), (6, 'prostobank'), (7, 'minfin'), (8, 'ukrgazbank'), (9, 'pumb'), (10, 'pravex'), (11, 'alphabank')]),
        ),
    ]
