# Generated by Django 2.2.16 on 2020-10-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20201011_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
    ]
