# Generated by Django 2.2.16 on 2020-10-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20201012_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='user',
        ),
    ]
